### ISSUE TITLE
System Overview

### ISSUE THREAD

**Issue by JamesMcSweeney** [JamesMcSweeney/CSC431#2]
write the System Overview for the SAS

**Comment by noahfjaccard** [comment]
**1.1 System Overview**
The Coronapyrus system includes the Coronapyrus package itself, and the app/bot that it creates on either Slack or Discord. The package itself does all of the behind-the-scenes heavy-work so that the app/bot can function as seamlessly as possible for user clarity. The package includes the ability to scrape data from the John Hopkins University coronavirus database or scrape article data from various coronavirus articles online. The package then formats the data into the user-specified format. The package invokes other open-source packages to format the data. Two alternate packages used are the Pandas and the Matplotlib, both for visualizing the data. This all happens within the package itself. The bot is the user's access to the Coronapyrus features. The bot is the input/output, while the package itself does all the work.

The pipeline for the Coronapyrus package and bot is as follows: (1) A Slack App or Discord Bot is create on a server by an admin. (2) Once the bot is created, any user in the server can request information from the app/bot. This could be a data request and the request's parameters, a help request that returns how to use the app/bot, or a source request that dictates where the data is taken from. (3) The app/bot sends the request to the package. Using the user-provided parameters, the app/bot fills the scope and format classes and passes those classes to the Coronapyrus package. (4) The package processes the data using its classes. (5) The package returns the data back to the app/bot. (6) The app/bot returns and prints the data to the specified chat room in the server. 

This is a two-tiered service. The Coronapyrus package itself allows the processing of data requested. While the user-centric app/bot allows the requests and output within Slack or Discord.
